package com.example.ui

enum class AppLanguage(val code: String, val displayName: String) {
    ENGLISH("en", "English"),
    HINDI("hi", "हिंदी (Hindi)"),
    HINGLISH("hinglish", "Hinglish")
}

data class StringsDefinition(
    val appTitle: String,
    val calendar: String,
    val tasks: String,
    val progress: String,
    val settings: String,
    val today: String,
    val month: String,
    val week: String,
    val day: String,
    val addEvent: String,
    val editEvent: String,
    val addTask: String,
    val editTask: String,
    val title: String,
    val date: String,
    val startTime: String,
    val endTime: String,
    val category: String,
    val reminder: String,
    val repeat: String,
    val notes: String,
    val cancel: String,
    val save: String,
    val delete: String,
    val markImportant: String,
    val searchPlaceholder: String,
    val noEventsToday: String,
    val noTasksToday: String,
    val studyTimetable: String,
    val todaysProgress: String,
    val completed: String,
    val pending: String,
    val totalStudyTime: String,
    val upcomingImportant: String,
    val studentMode: String,
    val studentModeDesc: String,
    val appearance: String,
    val light: String,
    val dark: String,
    val system: String,
    val language: String,
    val timeFormat: String,
    val firstDayOfWeek: String,
    val exportCalendar: String,
    val importCalendar: String,
    val clearData: String,
    val clearDataConfirm: String,
    val dataExported: String,
    val dataImported: String,
    val quickAddPlaceholder: String,
    val filterAll: String,
    val filterToday: String,
    val filterUpcoming: String,
    val filterCompleted: String,
    val priorityHigh: String,
    val priorityMedium: String,
    val priorityLow: String,
    val reschedule: String,
    val account: String,
    val signIn: String,
    val signUp: String,
    val signOut: String,
    val email: String,
    val password: String,
    val confirmPassword: String,
    val forgotPassword: String,
    val continueAsGuest: String,
    val guestAccount: String,
    val notSignedIn: String,
    val resetPasswordSent: String,
    val switchAccount: String,
    val fullName: String
)

val EnglishStrings = StringsDefinition(
    appTitle = "DayPlan Calendar",
    calendar = "Calendar",
    tasks = "Tasks",
    progress = "Progress",
    settings = "Settings",
    today = "Today",
    month = "Month",
    week = "Week",
    day = "Day",
    addEvent = "Add Event",
    editEvent = "Edit Event",
    addTask = "Add Task",
    editTask = "Edit Task",
    title = "Title",
    date = "Date",
    startTime = "Start Time",
    endTime = "End Time",
    category = "Category",
    reminder = "Reminder",
    repeat = "Repeat",
    notes = "Notes",
    cancel = "Cancel",
    save = "Save",
    delete = "Delete",
    markImportant = "Mark as Important",
    searchPlaceholder = "Search events, tasks, notes...",
    noEventsToday = "No events scheduled for this day",
    noTasksToday = "No tasks for this day",
    studyTimetable = "📚 Today's Study Timetable",
    todaysProgress = "Today's Progress",
    completed = "Completed",
    pending = "Pending",
    totalStudyTime = "Total Study Time",
    upcomingImportant = "⭐ Upcoming Important",
    studentMode = "Student Study Mode",
    studentModeDesc = "Enables subject planner, DPP, tests, and timetable",
    appearance = "Appearance",
    light = "Light",
    dark = "Dark",
    system = "System Default",
    language = "Language",
    timeFormat = "12/24-Hour Format",
    firstDayOfWeek = "First Day of Week",
    exportCalendar = "Export Calendar & Tasks",
    importCalendar = "Import Calendar & Tasks",
    clearData = "Clear All Data",
    clearDataConfirm = "Are you sure you want to erase all events and tasks?",
    dataExported = "Data exported to clipboard successfully!",
    dataImported = "Data imported successfully!",
    quickAddPlaceholder = "Quick add a task for today...",
    filterAll = "All",
    filterToday = "Today",
    filterUpcoming = "Upcoming",
    filterCompleted = "Done",
    priorityHigh = "High Priority",
    priorityMedium = "Medium Priority",
    priorityLow = "Low Priority",
    reschedule = "Reschedule",
    account = "Account & Profile",
    signIn = "Sign In",
    signUp = "Sign Up",
    signOut = "Sign Out",
    email = "Email",
    password = "Password",
    confirmPassword = "Confirm Password",
    forgotPassword = "Forgot Password?",
    continueAsGuest = "Continue as Guest",
    guestAccount = "Guest Account",
    notSignedIn = "Not Signed In",
    resetPasswordSent = "Password reset link sent to your email!",
    switchAccount = "Switch Account",
    fullName = "Full Name"
)

val HindiStrings = StringsDefinition(
    appTitle = "DayPlan कैलेंडर",
    calendar = "कैलेंडर",
    tasks = "कार्य (Tasks)",
    progress = "प्रगति (Progress)",
    settings = "सेटिंग्स",
    today = "आज",
    month = "माह",
    week = "सप्ताह",
    day = "दिन",
    addEvent = "इवेंट जोड़ें",
    editEvent = "इवेंट बदलें",
    addTask = "कार्य जोड़ें",
    editTask = "कार्य बदलें",
    title = "शीर्षक",
    date = "दिनांक",
    startTime = "शुरुआती समय",
    endTime = "समाप्ति समय",
    category = "श्रेणी",
    reminder = "रिमाइंडर",
    repeat = "दोहराव (Repeat)",
    notes = "नोट्स",
    cancel = "रद्द करें",
    save = "सुरक्षित करें",
    delete = "हटाएं",
    markImportant = "महत्वपूर्ण मार्क करें ⭐",
    searchPlaceholder = "इवेंट, कार्य या नोट्स खोजें...",
    noEventsToday = "इस दिन कोई इवेंट नहीं है",
    noTasksToday = "इस दिन कोई कार्य नहीं है",
    studyTimetable = "📚 आज का अध्ययन टाइमटेबल",
    todaysProgress = "आज की प्रगति",
    completed = "पूर्ण कार्य",
    pending = "शेष कार्य",
    totalStudyTime = "कुल अध्ययन समय",
    upcomingImportant = "⭐ आगामी महत्वपूर्ण",
    studentMode = "विद्यार्थी अध्ययन मोड",
    studentModeDesc = "विषय टाइमटेबल, डीपीपी, परीक्षा और होमवर्क सक्रिय करें",
    appearance = "दिखावट (थीम)",
    light = "लाइट",
    dark = "डार्क",
    system = "सिस्टम डिफ़ॉल्ट",
    language = "भाषा",
    timeFormat = "12/24-घंटे प्रारूप",
    firstDayOfWeek = "सप्ताह का पहला दिन",
    exportCalendar = "डेटा निर्यात करें (Export)",
    importCalendar = "डेटा आयात करें (Import)",
    clearData = "सभी डेटा साफ़ करें",
    clearDataConfirm = "क्या आप सभी इवेंट और कार्यों को मिटाना चाहते हैं?",
    dataExported = "डेटा क्लिपबोर्ड में कॉपी हो गया!",
    dataImported = "डेटा सफलतापूर्वक आयात हो गया!",
    quickAddPlaceholder = "आज के लिए नया कार्य जोड़ें...",
    filterAll = "सभी",
    filterToday = "आज",
    filterUpcoming = "आगामी",
    filterCompleted = "पूर्ण",
    priorityHigh = "उच्च प्राथमिकता",
    priorityMedium = "मध्यम",
    priorityLow = "कम",
    reschedule = "तारीख बदलें",
    account = "खाता एवं प्रोफ़ाइल",
    signIn = "साइन इन करें",
    signUp = "साइन अप करें",
    signOut = "साइन आउट",
    email = "ईमेल",
    password = "पासवर्ड",
    confirmPassword = "पासवर्ड की पुष्टि करें",
    forgotPassword = "पासवर्ड भूल गए?",
    continueAsGuest = "अतिथि के रूप में जारी रखें",
    guestAccount = "अतिथि खाता",
    notSignedIn = "साइन इन नहीं हैं",
    resetPasswordSent = "पासवर्ड रीसेट लिंक आपके ईमेल पर भेजा गया!",
    switchAccount = "खाता बदलें",
    fullName = "पूरा नाम"
)

val HinglishStrings = StringsDefinition(
    appTitle = "DayPlan Calendar",
    calendar = "Calendar",
    tasks = "Tasks",
    progress = "Progress",
    settings = "Settings",
    today = "Aaj",
    month = "Month",
    week = "Week",
    day = "Day",
    addEvent = "Event Add Karein",
    editEvent = "Event Edit Karein",
    addTask = "Task Add Karein",
    editTask = "Task Edit Karein",
    title = "Title",
    date = "Date",
    startTime = "Start Time",
    endTime = "End Time",
    category = "Category",
    reminder = "Reminder",
    repeat = "Repeat",
    notes = "Notes",
    cancel = "Cancel",
    save = "Save Karein",
    delete = "Delete Karein",
    markImportant = "Important Mark Karein ⭐",
    searchPlaceholder = "Events, tasks aur notes search karein...",
    noEventsToday = "Is din koi event schedule nahi hai",
    noTasksToday = "Is din koi task nahi hai",
    studyTimetable = "📚 Aaj ki Study Timetable",
    todaysProgress = "Aaj ki Progress",
    completed = "Completed Tasks",
    pending = "Pending Tasks",
    totalStudyTime = "Total Study Time",
    upcomingImportant = "⭐ Upcoming Important",
    studentMode = "Student Study Mode",
    studentModeDesc = "Subjects timetable, DPP, homework aur exams plan karein",
    appearance = "Appearance",
    light = "Light Mode",
    dark = "Dark Mode",
    system = "System Default",
    language = "Bhasha (Language)",
    timeFormat = "12/24 Hour Format",
    firstDayOfWeek = "Week ka Pehla Din",
    exportCalendar = "Calendar Export Karein",
    importCalendar = "Calendar Import Karein",
    clearData = "Sara Data Clear Karein",
    clearDataConfirm = "Kya aap saare events aur tasks delete karna chahte hain?",
    dataExported = "Data clipboard par copy ho gaya!",
    dataImported = "Data successfully import ho gaya!",
    quickAddPlaceholder = "Aaj ke liye quick task add karein...",
    filterAll = "Sabhi",
    filterToday = "Aaj",
    filterUpcoming = "Aane wale",
    filterCompleted = "Done",
    priorityHigh = "High Priority",
    priorityMedium = "Medium Priority",
    priorityLow = "Low Priority",
    reschedule = "Reschedule Karein",
    account = "Account & Profile",
    signIn = "Sign In Karein",
    signUp = "Sign Up Karein",
    signOut = "Sign Out Karein",
    email = "Email",
    password = "Password",
    confirmPassword = "Confirm Password",
    forgotPassword = "Password bhool gaye?",
    continueAsGuest = "Guest ki tarah continue karein",
    guestAccount = "Guest Account",
    notSignedIn = "Signed in nahi hain",
    resetPasswordSent = "Password reset link aapke email par bhej diya gaya hai!",
    switchAccount = "Account Switch Karein",
    fullName = "Poora Naam"
)

fun getStrings(language: AppLanguage): StringsDefinition {
    return when (language) {
        AppLanguage.ENGLISH -> EnglishStrings
        AppLanguage.HINDI -> HindiStrings
        AppLanguage.HINGLISH -> HinglishStrings
    }
}
